[webservers]
vm-test ansible_host=vm-test-proxmox-1.tailfd58bd.ts.net
# On ajoute la 506 ici pour qu'Ansible puisse la joindre en local la première fois
vm-portfolio-webserver ansible_host=192.168.192.56 

[portfolio]
vm-portfolio-webserver ansible_host=192.168.192.56
# Retry
