name: Proxmox-Deploy-Lab

on:
  push:
    branches: [ main ]

jobs:
  terraform-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Connexion du Runner au VPN (Utilise ton secret TAILSCALE_AUTHKEY)
      - name: Connect Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
        env:
          PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
          PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
          PM_API_URL: ${{ secrets.PM_API_URL }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -refresh=false
        env:
          PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
          PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
          PM_API_URL: ${{ secrets.PM_API_URL }}

      - name: Wait for VM to be ready
        run: sleep 60

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # On scanne l'IP Tailscale pour éviter le blocage "Host key verification failed"
          ssh-keyscan -H 100.104.1.90 >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: pip install ansible

      - name: Run Ansible playbook
        run: |
          ansible-playbook ansible/install_nginx.yml \
            -i "100.104.1.90," \
            --private-key ~/.ssh/id_ed25519 \
            -e "ansible_user=mila" \
            -e "tailscale_vm_authkey=${{ secrets.TAILSCALE_VM_AUTHKEY }}" \
            -v
