name: Infrastructure Drift Detection

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  drift-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Connect Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (Drift Check)
        id: plan
        run: |
          terraform plan -detailed-exitcode || exit_code=$?
          if [ ${exit_code} -eq 2 ]; then
            echo "DRIFT DETECTED: Difference entre Git et Proxmox"
            exit 1
          elif [ ${exit_code} -eq 0 ]; then
            echo "Infrastructure alignee."
          else
            echo "Erreur lors du plan."
            exit 1
          fi
        env:
          TF_VAR_proxmox_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_proxmox_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_proxmox_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
